### ISSUE TITLE
spring.data.redis.username is not being set

### ISSUE THREAD

**Issue by sntp** [pivotal-cf/java-cfenv#294]
### Describe the bug

CfEnv correctly sets redis credentials such as host, port and password in auto configuration but it doesn't set username, in my case it was required for connection to a9s redis 7 instance.

### Reproduction steps

1.
2.
3.
...

### Expected behavior

CfEnv populates all available spring data redis properties:

```
spring
  data:
    redis:
      host: 
      password: 
      port:
      username:
```

### Additional context

As a work-around I configured them manually:
```
spring:
  data:
    redis:
      host: ${vcap.services.redis.credentials.host}
      password: ${vcap.services.redis.credentials.redis.password}
      port: ${vcap.services.redis.credentials.redis.port}
      username: ${vcap.services.redis.credentials.redis.username}
```
