### ISSUE TITLE
CfSingleSignOnProcessor should set jwk-set-uri 

### ISSUE THREAD

**Issue by xyloman** [pivotal-cf/java-cfenv#85]
In order for applications that need to process OAuth2 tokens with the JwtDecoder, the property `spring.security.oauth2.resourceserver.jwt.jwk-set-uri ` should be set [CfSingleSignOnProcessor](https://github.com/pivotal-cf/java-cfenv/blob/master/java-cfenv-boot-pivotal-sso/src/main/java/io/pivotal/cfenv/boot/sso/CfSingleSignOnProcessor.java) so that [OAuth2ResourceServerJwtConfiguration.java](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/servlet/OAuth2ResourceServerJwtConfiguration.java#L65) builds the JwtDecoder bean.

**Comment by xyloman** [comment]
Otherwise with out this configuration an application has to set the jwk-set-uri property themselves with the information that comes from the service binding:

```
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${identity.auth_domain}/token_keys
          jwk-set-uri: ${vcap.services.identity.credentials.auth_domain}/token_keys
```
